# Generated by Django 2.2 on 2020-05-17 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='tests.Answer', unique=True),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_results', to='tests.Question', unique=True),
        ),
        migrations.AlterField(
            model_name='teststatresult',
            name='test_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_stat_results', to='tests.TestStat', unique=True),
        ),
    ]
